### ISSUE TITLE
license = MIT?

### ISSUE THREAD

**Issue by larshp** [fatihpense/zmimesync#1]
Hi,
Is the code released under MIT license?

See
https://help.github.com/articles/adding-a-license-to-a-repository/
for how to add a license file in the repository.

**Comment by fatihpense** [comment]
Hi Lars, yes it is MIT licensed. I will add the license immediately.

Thanks for pointing that out!

**Comment by fatihpense** [comment]
MIT Licenses are added to this repository and related service repository:
https://github.com/fatihpense/zmimesync_service

Thanks!
